version: '3'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/detyracloud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: detyracloud
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
